### ISSUE TITLE
initenv.sh on MacOS fails (crypt_r build error)

### ISSUE THREAD

**Issue by feld** [chatmail/server#520]
MacOS no longer ships a libcrypt as required by crypt_r, so you need to install one. If you use Brew this will work:

```shell
brew install libxcrypt
env LDFLAGS="-L$(brew --prefix libxcrypt)/lib" CFLAGS="-I$(brew --prefix libxcrypt)/include" ./scripts/initenv.sh
```

Now you have a working venv for doing the cmdeploy.

**Comment by adbenitez** [comment]
We should probably try to switch to Python standard lib, crypt_r is deprecated legacy lib

**Comment by lil5** [comment]
Also stopped working in Ubuntu 24.04 `Python 3.13.1`

**Comment by Simon-Laux** [comment]
Same on NixOS, there I also have to specify that I need `libxcrypt` in my shell to be able to run `./scripts/initenv.sh`:
```
nix-shell -p python3 libxcrypt
```

otherwise I get this error during dependency isntallation:
```
      src/_crypt_r.c:9:10: fatal error: crypt.h: No such file or directory
          9 | #include <crypt.h>
            |          ^~~~~~~~~
      compilation terminated.
```

**Comment by feld** [comment]
on FreeBSD I can't even pip install the chatmaild without removing the crypt-r dependency definition in `chatmaild/pyproject.toml`. My cookbook deployment on Debian also has it removed and everything continues to work. The only consumer is doveauth which has the import protected like this:

```
try:
    import crypt_r
except ImportError:
    import crypt as crypt_r
```

But Debian 12 and FreeBSD are also defaulting to Python 3.11 and the purpose of this crypt-r library is to support identical functionality in 3.13 as that is when things changed. For some reason we define it as:

```
"crypt-r >= 3.13.1 ; python_version >= '3.11'",
```

...which seems wrong. I think it really should have been `python_version >= '3.13'`

What we need to do is validate if the Python 3.13 crypt is fully compatible and allows Dovecot authentication of existing accounts to work with Python 3.13 without crypt-r.

**Comment by missytake** [comment]
With #852, the main deployment path for this repository will mean cloning the repository to the Debian 12 server itself, and running cmdeploy there - then we don't need to fix it for MacOS anymore. btw, it's already doable today, by passing `--ssh-host localhost` to `cmdeploy run`.

But it also means that requiring python3.13 right now would break the default installation path for Debian 12, the one OS we currently support. If we upgrade to Debian 13 soon (#476) we can require python3.13, before that it's premature I think.
